core/runner/package.json, core/runner/src/Configuration.ts, core/runner/src/NanoService.ts, core/runner/src/NanoServiceResponse.ts, core/runner/src/Runner.ts, core/runner/src/RunnerSteps.ts, core/runner/src/TriggerBase.ts, core/runner/src/index.ts, core/runner/src/types/JsonLikeObject.ts, core/runner/test/nanoservice-base.test.ts, core/workflow-helper/src/index.ts, makefile, nodes/control-flow/if-else@1.0.0/index.ts, nodes/control-flow/if-else@1.0.0/inputSchema.ts, nodes/control-flow/if-else@1.0.0/package.json, nodes/web/api-call@1.0.0/index.ts, nodes/web/api-call@1.0.0/inputSchema.ts, nodes/web/api-call@1.0.0/package.json, nodes/web/api-call@1.0.0/util.ts, package.json, pnpm-lock.yaml, triggers/http/src/HttpTrigger.ts
New features added:
- Json Schema validation for Nodes input and outputs
- Node base class changed to simplify the developer experience crating new nano services
- Upgraded the demo nodes using the new node base class
=> node base class changed and simlify

cli/src/commands/create/node.ts, cli/src/commands/create/project.ts, cli/src/index.ts, package.json
Implemented:
- nanoctl create node
=> new create node command implemented for testing

README.md, mint.json
Fix discord link
---
Fixed broken discord link in `mint.json` and `README.md`
=> Fix discord link

docs/d/introduction/nanoservices-concept.mdx
Fixed a type in nanoservice-concept
Thank you for your contribution!
=> Fixed a type in nanoservices-concept

core/runner/CHANGELOG.md, core/runner/package.json, core/runner/src/LocalStorage.ts, core/runner/test/localstorage.test.ts, core/shared/CHANGELOG.md, core/shared/package.json, core/workflow-helper/CHANGELOG.md, core/workflow-helper/package.json, docs/d/core-concepts/nodes.mdx, nodes/control-flow/if-else@1.0.0/CHANGELOG.md, nodes/control-flow/if-else@1.0.0/package.json, nodes/web/api-call@1.0.0/CHANGELOG.md, nodes/web/api-call@1.0.0/package.json, nodes/web/react@1.0.0/CHANGELOG.md, nodes/web/react@1.0.0/package.json, packages/cli/CHANGELOG.md, packages/cli/package.json, pnpm-lock.yaml, templates/node/CHANGELOG.md, templates/node/package.json, templates/ts-template/package.json, triggers/grpc/CHANGELOG.md, triggers/grpc/package.json, triggers/http/CHANGELOG.md, triggers/http/package.json, triggers/http/workflows/toml/countries.toml, triggers/http/workflows/xml/countries.xml, triggers/http/workflows/yaml/countries.yaml
This new version included the support for multiple configuration files, like:
- YAML
- XML
- TOML
---
The workflows could be created using multiple formats.
=> Implement yaml support

core/runner/CHANGELOG.md, core/runner/package.json, core/runner/src/NanoServiceResponse.ts, nodes/control-flow/if-else@1.0.0/CHANGELOG.md, nodes/control-flow/if-else@1.0.0/package.json, nodes/web/api-call@1.0.0/CHANGELOG.md, nodes/web/api-call@1.0.0/package.json, nodes/web/react@1.0.0/CHANGELOG.md, nodes/web/react@1.0.0/package.json, package.json, pnpm-lock.yaml, triggers/grpc/CHANGELOG.md, triggers/grpc/package.json, triggers/http/CHANGELOG.md, triggers/http/package.json
Allowing the Array type for the response.data;
---
This is required to extend the response data formats.
=> setSuccess accept JsonLikeObject[] for arrays

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/create/node.ts, pnpm-lock.yaml
This commit addresses a bug that prevented the successful creation of nodes with the class type. The issue has been resolved, and the functionality now works as expected.
=> fix: resolve issue when creating nodes of type 'class'

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/create/node.ts, packages/cli/src/commands/create/project.ts, packages/cli/src/commands/create/utils/Examples.ts, packages/cli/src/commands/create/workflow.ts, packages/cli/src/commands/dev/index.ts, packages/cli/src/index.ts, runtimes/python3/runner.py, runtimes/python3/server.py
This PR introduces the following enhancements to the CLI project:  
1. **Multiple Runtimes for `create project` Command**:  
- Added support for multiple runtimes in the `create project` command, allowing users to specify their preferred runtime environment when creating a new project.  
2. **Python3 Node in `create node` Command**:  
- Implemented the creation of Python3 nodes in the `create node` command, enabling users to generate Python3-compatible nodes seamlessly.  
3. **New `create workflow` Command**:  
- Introduced a new `create workflow` command to simplify the creation of workflows, reducing the manual effort required to set up and configure workflows.  
These changes improve the flexibility and usability of the CLI tool, making it easier for users to manage projects, nodes, …
=> Add multiple runtimes, Python3 node support, and create workflow command

.gitignore, runtimes/python3/nodes/generate_pdf/node.py, runtimes/python3/nodes/nodes.py, runtimes/python3/requirements.txt, triggers/http/src/nodes/examples/base64-pdf/index.ts, triggers/http/src/nodes/examples/index.ts, triggers/http/workflows/json/rentals-pdf.json
This PR introduces an **end-to-end automated sales reporting system** that utilizes **multi-runtime support** in nanoservice-ts, combining **TypeScript** for data processing and **Python3** for PDF generation.
---
- Queries the **PostgreSQL** database for sales records.
- Retrieves relevant fields: `id`, `product_name`, `total`, `quantity`, `price`.
- Ensures secure database interaction.
- Converts numerical fields (`total`, `quantity`, `price`) into the correct types.
- Normalizes data for consistent processing.
- Uses **FPDF** to generate a **professional, formatted PDF report**.
- Encodes the PDF **as a Base64 string** for easy transport.
- Converts the Base64 string **back into a downloadable PDF file**.
- Ensures the correct **content-type** (`application/pdf`) is returned.
---
- …
=> Automated Sales Report Generation (TypeScript + Python3)

README.md
Updated the Readme section
---
I added documentation installation process for easy navigation for individual that wants to contribute
--
_Reference any related issues or discussions (e.g., "Closes #123")._
---
_Outline the specific changes made in this pull request:_
- *Prerequisites**: Added the prerequisites need for the installation.
- **Installation**:Added a details installation to get the documentation running and local machine.
- **Contributing**: Added steps to contribute to the documentation
---
_Please ensure the following items are completed:_
---
_Add screenshots, GIFs, or other media to demonstrate the change._
---
_Any additional context or notes for reviewers?_
---
Thank you for your contribution!
=> Added documentation installation process

packages/cli/CHANGELOG.md, packages/cli/package.json
=> cli minor version 0.1.0

dockerfiles/Dockerfile, triggers/http/Dockerfile
Fix dockerfile
---
Install git for required dependency
---
---
---
---
_Add screenshots, GIFs, or other media to demonstrate the change._
---
---
Thank you for your contribution!
=> fix: dockerfile

infra/development/docker-compose.yml, infra/metrics/docker-compose.yml, infra/milvus/docker-compose.yml
Docker network shared between the multiple docker compose files.
=> fixed docker-compose.yaml files adding a network

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/monitor/index.ts, packages/cli/src/commands/monitor/monitor-component.tsx, pnpm-lock.yaml, triggers/http/.env.example
This PR introduces a new `monitor` command to the CLI, enabling real-time performance monitoring of workflows and nanoservices. The feature includes:
* 📟 **Terminal UI:** Live display of time, memory, CPU, errors, and requests per workflow and node.
* 🌐 **Web Dashboard Support:** `--web` flag opens a browser-based metrics view.
* 📊 Powered by **Prometheus** queries for accurate, up-to-date metrics.
This lays the foundation for cross-environment observability from both CLI and browser.
=> Feature: CLI Monitor Command (Terminal & Web Dashboard)

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/create/project.ts, triggers/http/.env.example, triggers/http/Dockerfile.dev, triggers/http/infra/docker-compose.yml, triggers/http/package.json
Fixed issues found in:
- pnpm run infra:dev: workflow not found
- removed .env.local from docker file
- moved docker compose files to infra dir
=> centralized docker-compose files.

packages/cli/src/commands/deploy/index.ts
Add public option to deploy command for nanoservice visibility
---
_Add public option to deploy command for nanoservice visibility
=> APB-482 Add public option to deploy command for nanoservice visibility

triggers/http/public/metric/index.html
feature: add 'workflows' and 'nodes' filters, integrate them with queries, and preserve on localStorage)
---
Add filters to metrics web view.
=> feature: add 'workflows' and 'nodes' filters, integrate them with queries, and preserve on localStorage

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/deploy/index.ts, triggers/http/src/HttpTrigger.ts, triggers/http/src/opentelemetry_metrics.ts
add /metrics endpoint to expose Prometheus metrics
---
add /metrics endpoint to expose Prometheus metrics
=> APB-483 feat: add /metrics endpoint to expose Prometheus metrics

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/monitor/static-web-server.ts, packages/cli/src/commands/monitor/static/index.html
Labels request is responding a 404 error. The proxy has been updated.
=> fixed monitor issues loading labels

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/create/node.ts, packages/cli/src/commands/create/project.ts, packages/cli/src/commands/generate/NodeFileWriter.ts, packages/cli/src/commands/generate/NodeGenerator.ts, packages/cli/src/commands/generate/RegisterNode.ts, packages/cli/src/commands/generate/index.ts, packages/cli/src/commands/generate/prompts/create-node-manifest.system.ts, packages/cli/src/commands/generate/prompts/create-node.system.ts, packages/cli/src/commands/generate/prompts/register-node.system.ts, packages/cli/src/commands/monitor/static/index.html, packages/cli/src/index.ts, pnpm-lock.yaml, triggers/http/public/metric/index.html, triggers/http/src/Nodes.ts, triggers/http/workflows/json/loadtest.json
This PR introduces a new CLI command for the `nanoctl` tool that empowers developers to generate nanoservice Nodes using OpenAI’s API.
```bash
npx nanoctl@latest generate ai-node \
--name "my-new-node" \
--prompt "Create a nanoservice that reads a file from disk" \
--api-key $OPENAI_API_KEY
```
Optional parameters:
* `--type`: Type of output file, defaults to `"class"`.
* `--language`: Programming language to generate (defaults to `"typescript"`).
* `--api-key`: OpenAI API key (falls back to `OPENAI_API_KEY` environment variable if omitted).
---
* Sends the provided prompt to OpenAI to generate a complete Node using the `@nanoservice-ts` structure.
* Cleans up markdown wrappers (` ```typescript `).
* Saves the generated file to the appropriate `./nodes/` directory.
* Automatically …
```
=> New Feature: AI-Powered Node Generation via `nanoctl generate ai-node`

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/chat/ARCHITECTURE.md, packages/cli/src/commands/chat/README.md, packages/cli/src/commands/config/index.ts, packages/cli/src/commands/generate/NodeFileWriter.ts, packages/cli/src/commands/generate/NodeGenerator.ts, packages/cli/src/commands/generate/RegisterNode.ts, packages/cli/src/commands/generate/index.ts, packages/cli/src/commands/generate/prompts/create-node.system.ts, packages/cli/src/commands/generate/prompts/create-readme.system.ts, packages/cli/src/commands/generate/prompts/register-node.system.ts, packages/cli/src/commands/monitor/index.ts, packages/cli/src/commands/monitor/monitor-component.tsx, packages/cli/src/index.ts, packages/cli/src/services/utils.ts
Included Features
* Added the `--update` flag to the `generate ai-node` command.
* Allows updating existing nodes instead of creating new ones from scratch.
* Useful for workflows that evolve over time without losing prior configuration.
The `generate ai-node` command now also creates or updates the following:
* `config.json`: Base configuration file for the generated node.
* `README.md`: Auto-generated documentation with a default template.
* `package.json`: Automatically extended with:
* `"name"` of the node.
* Initial `"version"` (default `0.1.0`).
* `"description"` based on input or node name.
* Appropriate `"dependencies"` and `"devDependencies"`.
* Both `monitor` and `monitor --web` now use the **auth token generated by the `login` command**.
* Enables secure access to metrics, …
=> Enhancements to generate ai-node and monitor Commands

packages/cli/CHANGELOG.md, packages/cli/package.json, packages/cli/src/commands/search/index.ts, packages/cli/src/commands/search/indexer.ts, packages/cli/src/commands/search/search.ts, packages/cli/src/index.ts, pnpm-lock.yaml
This PR enhances the documentation search functionality by implementing a sophisticated search engine that indexes both Markdown and JSON files, with special handling for JSON field weights and improved context formatting for AI responses.
- **Multi-format Support**: Indexes both Markdown (`.md`) and JSON (`.json`) files
- **Smart JSON Field Weighting**:
- Name fields: 3x weight
- Description fields: 2x weight
- Type fields: 1.5x weight
- **Intelligent Word Processing**:
- Handles singular/plural forms
- Removes common stop words in English and Spanish
- Ignores technical terms (function, class, const, etc.)
- Special handling for markdown syntax
- **Context-Aware Results**:
- Shows relevance scores for each source
- Formats JSON content for better readability
- Maintains token limits for …
=> Enhanced Documentation Search Command

packages/cli/src/commands/publish/workflow.ts, packages/cli/src/commands/search/nodes.ts
Fix publish workflow content type
---
Fix publish workflow fetch content type
---
Thank you for your contribution!
=> Fix publish workflow content type

packages/cli/src/commands/install/index.ts, packages/cli/src/commands/install/workflow.ts, packages/cli/src/commands/publish/node.ts
Fix install workflow command
---
Register install workflow command
Fix the install workflow command token and remove unnecessary code
=> Fix install workflow command

packages/cli/src/commands/create/project.ts, packages/cli/src/index.ts
feat: version validation and clone from release
---
feat: version validation and clone from release
=> feat: version validation and clone from release
